### ISSUE TITLE
Dropping blocks is not functional well

### ISSUE THREAD

**Issue by nobuyo** [13J-Programmers/3J_class_project#10]
# Steps to Reproduce:

```
1. Run a unity project;
2. Click to generate block(without move block);
3. Press space key for few seconds;
```
# Actual Results:

```
The project does not stop until forced tremination.
```
# Expected Results:

```
The Game drops a block every push space key.
```

**Comment by tex2e** [comment]
I recognized

new block is expected to be created when the dropping block is landed.
However, it is sometimes created before the dropping block is landed.

therefore, I add "BlockPool" tag to landed block.
this fix is to solve the above problem temporarily.

**Comment by nobuyo** [comment]
Thank you for quick responce.

In KeyAction.cs,From line 70 is as follows: 
.....
        if (Input.GetKey("space")) ....
.....
But to solve the problem,
 I guess it should use "GetKeyDown" method to getting the insertion of space key.

Please confirm (or check) if it’s correct.

**Comment by tex2e** [comment]
I changed to use GetKeyDown method.
however, it is not solve the problem.
